language: "en"
languages:
  - "en"
  - "de"
#eg: wooden_axe
disabled-weapons: ["wooden_axe"]
#eg: splash_potion
disabled-causes: []
#Track stats if tracked person is in creative?
allowCreative: false
#In minutes
saveInterval: 5