name: MischiefStats
version: 0.0.1
author: sven@wollinger.email
main: com.mischiefsmp.stats.MischiefStats
api-version: 1.18
depend: ["MischiefCore"]
commands:
  stats:
    description: View stats
    usage: /<command>
permissions:
  stats.view:
    description: View your own stats
    default: true
  stats.view.others:
    description: View someone elses stats
    default: op
  stats.reset:
    description: Reset your own stats
    default: op
  stats.reset.others:
    description: Reset someone elses stats
    default: op