name: MischiefStats
version: 0.0.1
author: sven@wollinger.email
main: com.mischiefsmp.stats.MischiefStats
api-version: 1.18
depend: ["MischiefCore"]
commands:
  stats:
    description: View stats
    usage: /<command>